---
title: "Bayesian Rating Curve"
mathjax: "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
---
```{r setup, include=FALSE}
Sys.setlocale("LC_ALL","is_IS")
```

```{r echo=FALSE, include=FALSE}
library(stargazer,quietly=TRUE)
```  
   
      
```{r echo=FALSE}
plotlist=model1()
a=exp(plotlist$mu[1,])
b=plotlist$mu[2,]
c_hat=min(plotlist$RC$w)-exp(plotlist$t_m[1,])
varappr=mean(plotlist$varappr)
predict=1.96*sqrt(varappr)
```

Formula for rating curve: $$\ \hat{Q}(W) = a \cdot (W - \hat{c})^b = `r a` \cdot (W - `r c_hat` )^{ `r b`}$$
    
Formula for lower predictive: $$\ \hat{Q}_{lower}(W) = \hat{Q}(W) \cdot {(e^{1.96})}^ {-\sigma_{\epsilon}} = \hat{Q}(W) \cdot {(e^{1.96})}^ {`r -varappr`} = \hat{Q}(W) \cdot `r exp(-predict)`$$

Formula for upper predictive: $$\ \hat{Q}_{lower}(W) = \hat{Q}(W) \cdot {(e^{1.96})}^ {\sigma_{\epsilon}} = \hat{Q}(W) \cdot {(e^{1.96})}^ {`r varappr`} = \hat{Q}(W) \cdot `r exp(predict)`$$

```{r results='asis',echo=FALSE}
stargazer(plotratingcurve1()$tafla,type="latex",summary=FALSE, title=input$name,header=FALSE,digits=3,digits.extra=3)
```

```{r,echo=FALSE}
if(length(plotratingcurve1())!=0)
    if(class(plotratingcurve1()[[1]])[1]=="gg")
        plotratingcurve1()[[1]]
```
   
   
```{r,echo=FALSE}
if(length(plotratingcurve1())>=2)
    if(class(plotratingcurve1()[[2]])[1]=="gg")
        plotratingcurve1()[[2]]
```
   
   
```{r,echo=FALSE}
if(length(plotratingcurve1())>=3)
    if(class(plotratingcurve1()[[3]])[1]=="gg")
        plotratingcurve1()[[3]]
```
   
   
```{r,echo=FALSE}
if(length(plotratingcurve1())>=4)
    if(class(plotratingcurve1()[[4]])[1]=="gg")
        plotratingcurve1()[[4]]
```

```{r results='asis',echo=FALSE}

stargazer(plotratingcurve2()$tafla,type="latex",summary=FALSE, title=input$name,header=FALSE,digits=3,digits.extra=3)
```

```{r,echo=FALSE}
if(length(plotratingcurve2())!=0)
    if(class(plotratingcurve2()[[1]])[1]=="gg")
        plotratingcurve2()[[1]]
```
   
   
```{r,echo=FALSE}
if(length(plotratingcurve2())>=2)
    if(class(plotratingcurve2()[[2]])[1]=="gg")
        plotratingcurve2()[[2]]
```
   
   
```{r,echo=FALSE}
if(length(plotratingcurve2())>=3)
    if(class(plotratingcurve2()[[3]])[1]=="gg")
        plotratingcurve2()[[3]]
```
   
   
```{r,echo=FALSE}
if(length(plotratingcurve2())>=4)
    if(class(plotratingcurve2()[[4]])[1]=="gg")
        plotratingcurve2()[[4]]
```
